### ISSUE TITLE
example build does not work

### ISSUE THREAD

**Issue by fibo** [toxicFork/react-three-renderer-example#6]
When I run the _Simple_  I get

```
Error: Cannot find module 'react/lib/getNativeComponentFromComposite' from '/home/io/github.com/fibo/tris3d-canvas/node_modules/react-three-renderer/lib'
```

**Comment by toxicFork** [comment]
That is probably because of using newest react version, I will need to
modify the package json to restrict to 15.1 until compatibility is
restored, apologies for the inconvenience

**Comment by fibo** [comment]
thanks, I solved it using the version recommended
