### ISSUE TITLE
React 15.2.0 not compatible with react-three-renderer

### ISSUE THREAD

**Issue by lachlantweedie** [toxicFork/react-three-renderer-example#7]
Temp fix is to revert package.json to this 6e8ebb28d7402da458849b63e944ee95bf90d9c7 commit to get examples working.

**Comment by toxicFork** [comment]
Isn't 6e8ebb2 the latest commit? :)

**Comment by lachlantweedie** [comment]
Sorry! That's the commit that's seemed to break things I think? I grabbed the package.json from this version 93fbde1d3b84d6a4f3bc08ca68677a5b92e89efa :) 

(I know this is already and issue on react-three-renderer but thought it might be helpful to get things up and running for others)

**Comment by toxicFork** [comment]
Ah no this commit is supposed to fix things, are you having incompatibility issues on the latest?

**Comment by lachlantweedie** [comment]
Ah sorry! I must have done something wrong in initial setup. I just tried to replicate the issue and everything's fine whoops.. :/ Will post if I find my mistake!
